### ISSUE TITLE
Use multiple words for the same emoji

### ISSUE THREAD

**Issue by LucasCtrl** [start-again/spookyBot#10]
## Feature Request

**Describe the solution you'd like**
To avoid having to create several objects for the same emoji, why not use an array containing all the words?

**New translation file structure**
Before:
```js
{
  name: 'halloween',
  emoji: '🎃',
},
{
  name: 'pumpkin',
  emoji: '🎃',
}
```

After:
```js
{
  name: ['halloween', 'pumpkin'],
  emoji: '🎃',
}
```

**Comment by matteoauger** [comment]
Hello, may I work on it ? :)

**Comment by LucasCtrl** [comment]
Yes, no problem on my side! I look forward to your PR 😉

**Comment by mgomez08** [comment]
Hi!
Can I work on this for the Spanish language?
