### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by LucasCtrl** [start-again/spookyBot#11]
Hi!
Can I work on this for the Spanish language?

_Originally posted by @mgomez08 in https://github.com/LucasCtrl/spookyBot/issues/10#issuecomment-703123646_

**Comment by LucasCtrl** [comment]
You can add more words if you would like to but the [original file](https://github.com/LucasCtrl/spookyBot/blob/main/lang/es.js) already exist 😉

**Comment by mgomez08** [comment]
> You can add more words if you would like to but the [original file](https://github.com/LucasCtrl/spookyBot/blob/main/lang/es.js) already exist

That's what I meant, thank you!

**Comment by ALMerrill** [comment]
This one can probably be closed at this point

**Comment by LucasCtrl** [comment]
Closed with #14
