### ISSUE TITLE
Wrong informations

### ISSUE THREAD

**Issue by LucasCtrl** [start-again/spookyBot#15]
## Bug Report

**Current Behavior**
The information displayed in the user activity section is not correct when referring to the console.

Data in the console
![image](https://user-images.githubusercontent.com/19686996/94996657-3bbec480-05a6-11eb-9d3d-88c1f3dd1a9d.png)
Data displayed in the activity section:
- 1 server
- 3 users

**Comment by illusi0nary** [comment]
I added a PR for this issue: https://github.com/LucasCtrl/spookyBot/pull/22

**Comment by LucasCtrl** [comment]
Closed with #22
