### ISSUE TITLE
Contributing Request

### ISSUE THREAD

**Issue by InternetRamen** [start-again/spookyBot#23]
Could I contribute to this project?

I would like to add a command that calculates the amount of time you have to wait for a PR to be matured when given a PR start date.

I am also open to coding whatever commands you need.

**Comment by LucasCtrl** [comment]
I don't think if this command is very useful.
I leave this issue open to give me time for reflection.

**Comment by InternetRamen** [comment]
@LucasCtrl I am also open to code any ideas you have.

**Comment by illusi0nary** [comment]
@InternetRamen  why don't you come up with own ideas ? That would be much more fun =)

**Comment by InternetRamen** [comment]
Alright! I'll try my best to think of commands related to October

**Comment by illusi0nary** [comment]
Perfect can't wait for it. 
If you have some let us know.

I will close this issue for now. You can freely create a new one.
