### ISSUE TITLE
Feature: Halloween Bot Scare

### ISSUE THREAD

**Issue by illusi0nary** [start-again/spookyBot#30]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The bot reacts to the command boo!booh and joins your current voice channel and plays randomly a sound to scare you and your companions in the channel. A real laughter for everyone who is present in the channel! There is for the MVP Feature no spam protection nor queuing implemented.

**Describe the solution you'd like**
The MVP is already implemented. The command is added and the behaviour is also present.

**Describe alternatives you've considered**
As extensions which would be good #hacktoberfest issues:
Create a queue for the Bot
Create a anti-spam protection (each user can use it max 3 times in 10 minutes i.e.)
Create an interface to upload custom sounds to the Bot 

**Teachability, Documentation, Adoption, Migration Strategy**
The use is with a special command ${prefix}!booh - after that the bot joins the voice channel you are currently present in and plays a sound. After the playback is finished the bot disappeared like a ghost! :ghost:

**Comment by ghost** [comment]
This would be very easy and I can implement it. Using ffmpeg

**Comment by ghost** [comment]
@LucasCtrl , is it possible to install FFMPeg directly to heroku? instead of putting a ffmpeg.exe or .deb in the source code.
Also you would need to update the building.md if that's the case

**Comment by illusi0nary** [comment]
@dragonDScript  the first initial MVP is already implemented and open for review #31

**Comment by LucasCtrl** [comment]
> @LucasCtrl , is it possible to install FFMPeg directly to heroku? instead of putting a ffmpeg.exe or .deb in the source code.

I don't know for FFMPeg, I using my own VPS

> Also you would need to update the building.md if that's the case

We need to write a little doc about the building part as we have the testing part (Maybe we can improve it @ALMerrill)

**Comment by illusi0nary** [comment]
After the review from @LucasCtrl  i removed the redudant check for the message. 
It is not needed because we already have a check in beforehand if that command exists.

**Comment by ghost** [comment]
FFmpeg is a library that lets you, for example in this case, play music to a discord voice channel. More info about ffmpeg:
<a href="https://ffmpeg.org/" target="_blank">FFMpeg website</a>
