### ISSUE TITLE
Feature Extension HBS: Remove the public message after a configurable time

### ISSUE THREAD

**Issue by illusi0nary** [start-again/spookyBot#36]
**Feature Extension of the Halloween Bot Scare (HBS)**
Currently the bot sends you a message if you are not present in a voice channel. This message remains in the channel forever. 

**Details**
If you request the bot to scare you and your companions and you are not present in a voice channel it is writing you a reply message. This reply message should be deleted after a configurable time in order to prevent the bot from spamming a discord channel.

**Edit**:
The message can also be used as a DM instead of a global present message. (as suggested by @ALMerrill )

**Comment by ALMerrill** [comment]
Could we just have the bot DM you that you aren't in a voice channel instead of posting in a channel?

**Comment by illusi0nary** [comment]
Sure :-) @ALMerrill If you want to implement it go for it

**Comment by ALMerrill** [comment]
Yeah I’d be happy to, I’ll take this

**Comment by illusi0nary** [comment]
@ALMerrill  i assigned it to you happy coding :-)
