### ISSUE TITLE
React when mention someone

### ISSUE THREAD

**Issue by LucasCtrl** [start-again/spookyBot#37]
## Feature Request
It might be nice to get the bot to react to messages when someone is mentioned.

**Details**
The robot should react to the message when a person is mentioned. However, the username of the person on the server must contain `spooky`. 
It is also necessary to be careful that it is not the person's tag but his username that is taken into consideration.
**e.g.**: *LucasAlt#7887* is my tag but my username on some servers is *SpookyAlt*

**Comment by hannesfant** [comment]
> However, the username of the person on the server must contain spooky.

As in the name of the mentioned user or the one sending the message with the mention?

**Comment by LucasCtrl** [comment]
The mentionned one

**Comment by hannesfant** [comment]
I'll go ahead and add this then if you don't have anything against it

**Comment by LucasCtrl** [comment]
You can do it!
