### ISSUE TITLE
Add spanish language file

### ISSUE THREAD

**Issue by ALMerrill** [start-again/spookyBot#5]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I wanted to add a Spanish language file copying the English words to Spanish

**Describe the solution you'd like**
I added a Spanish file, with the addition of some extra words that also have the same meaning.

**Teachability, Documentation, Adoption, Migration Strategy**
It looks like just adding the file will allow it work one the PR is merged

PR: https://github.com/LucasCtrl/spookyBot/pull/3

**Comment by LucasCtrl** [comment]
Closed with PR #3
