### ISSUE TITLE
Add support for the Dutch language

### ISSUE THREAD

**Issue by tmttn** [start-again/spookyBot#8]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I would like to add support for the Dutch language

**Describe the solution you'd like**
Adding a nl.js file with the necessary words should do the trick.

**Describe alternatives you've considered**
-

**Teachability, Documentation, Adoption, Migration Strategy**
It should automatically work

**Comment by LucasCtrl** [comment]
You can do it, it's not a problem for me 😉

**Comment by ghost** [comment]
I know someone who speak Dutch. Maybe he can do something.

**Comment by tmttn** [comment]
@dragonDScript I speak Dutch (and created a PR #13 ) :-)

**Comment by ghost** [comment]
Fine.

**Comment by LucasCtrl** [comment]
Close with #13
