### ISSUE TITLE
Multi-words filter

### ISSUE THREAD

**Issue by LucasCtrl** [start-again/spookyBot#9]
## Bug Report

**Current Behavior**
In a translation file, multi-part words are not taken into account.
e.g.: "abend vor allerheiligen" will not be detected

**Possible Solution**
Change the operating principle of the filter. For the moment, the message is split after each space. Then the different words are compared against the words in the translation file.

**Comment by ALMerrill** [comment]
I created a pull request for this [here](https://github.com/LucasCtrl/spookyBot/pull/25). I need to test it locally, but I'm not sure how to do that. Could I get some help with that?
